#! /usr/bin/env python

"""short demo query"""

import psycopg2

with psycopg2.connect("") as conn:  # we rely on the PG* variables to be set
    with conn.cursor() as cur:
        cur.execute(
            "select * from events where args->>'_from' = %s order by blocknumber, transactionIndex, logIndex",
            ("0x1efb2a9ec48c10de786c837699129073f4a4429a",),
        )
        rows = cur.fetchall()

for x in rows:
    print(x)
