version: 2.1

templates:
  tagged-filter: &tagged-filter
    tags:
      only: /[0-9]+(\.[0-9]+)*/

executors:
  ubuntu-builder:
    docker:
      - image: trustlines/builder:master53
    working_directory: ~/repo

# define some common commands
# see https://circleci.com/docs/2.0/configuration-reference/#commands-requires-version-21
commands:
  create-venv:
    description: "Create venv"
    steps:
      - run:
          name: Create python venv
          command: |
            python3.8 -m venv venv
            venv/bin/pip install -c constraints.txt pip wheel setuptools

  config-path:
    description: "set environment variables and change PATH"
    steps:
    - run:
        name: Configuring PATH
        command: |
          echo 'export PATH=~/bin:~/repo/venv/bin:${PATH}' >> ${BASH_ENV}
          # echo ' . ~/.nvm/nvm.sh' >> ${BASH_ENV}

jobs:
  install:
    executor: ubuntu-builder
    steps:
      - checkout
      - config-path
      - restore_cache:
          key: venv-{{ checksum "constraints.txt" }}-{{ checksum "requirements.txt" }}
      - create-venv
      - run:
          name: Install requirements
          command: |
            pip install -c constraints.txt -r requirements.txt
      - save_cache:
          key: venv-{{ checksum "constraints.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: Install package
          command: |
            pip install -c constraints.txt .
      - run:
          name: Verify installed packages have compatible dependencies
          command: |
            pip check
      - run:
          name: Build distribution
          command: |
            python setup.py sdist
            pip wheel --no-deps -w ./dist .
      - persist_to_workspace:
          root: "~"
          paths:
            - repo

  install-python39:
    executor: ubuntu-builder
    steps:
      - checkout
      - config-path
      - create-venv
      - run:
          name: Install requirements and package with python
          command: |
            venv/bin/pip install -c constraints.txt tox
            tox -e py39

  check-dist:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Twine check
          command: |
            twine check dist/*

  upload-pypi:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Upload to pypi
          command: |
            twine upload dist/*

  run-flake8:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run flake8
          command: |
            flake8 print-logs run-query setup.py src tests

  run-black:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run black
          command: |
            black --check print-logs run-query setup.py src tests

  run-pytest:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run pytest
          command: |
            pytest tests

  run-mypy:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run mypy
          command: |
            mypy --ignore-missing-imports src tests

  build-docker-image:
    executor: ubuntu-builder
    environment:
      DOCKER_REPO: trustlines/py-eth-index
      LOCAL_IMAGE: index

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build . -t $LOCAL_IMAGE
      - run:
          name: Save docker image
          command: |
            mkdir -p ~/images
            docker save --output ~/images/$LOCAL_IMAGE.tar $LOCAL_IMAGE
      - persist_to_workspace:
          root: "~"
          paths:
            - images

  deploy-docker-image:
    executor: ubuntu-builder
    environment:
      DOCKER_REPO: trustlines/py-eth-index
      LOCAL_IMAGE: index
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: '~'
      - run:
          name: Load docker image
          command: |
            docker load --input ~/images/$LOCAL_IMAGE.tar
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Upload tagged release
          command: |
            version=$(docker run --rm $LOCAL_IMAGE --version | tr '+' '_')
            echo "Tagging with $version"
            docker tag $LOCAL_IMAGE $DOCKER_REPO:$version
            docker push $DOCKER_REPO:$version
      - run:
          name: Upload latest
          command: |
            docker tag $LOCAL_IMAGE $DOCKER_REPO:latest
            docker push $DOCKER_REPO:latest
  run-end2end-tests:
    executor: ubuntu-builder
    environment:
      DOCKER_REPO: trustlines/py-eth-index
      LOCAL_IMAGE: index
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: '~'
      - run:
          name: Checkout end2end repo
          command: |
            git clone https://github.com/trustlines-protocol/end2end.git
      - run:
          name: Load docker image
          command: |
            docker load --input ~/images/$LOCAL_IMAGE.tar
      - run:
          name: run end2end tests
          command: |
            docker tag $LOCAL_IMAGE $DOCKER_REPO
            cd end2end
            ./run-e2e.sh

workflows:
  version: 2
  default:
    jobs:
      - install:
          filters:
            <<: *tagged-filter

      - install-python39:
          filters:
            <<: *tagged-filter

      - run-flake8:
          requires:
            - install
          filters:
            <<: *tagged-filter

      - run-black:
          requires:
            - install
          filters:
            <<: *tagged-filter

      - run-pytest:
          requires:
            - install
          filters:
            <<: *tagged-filter

      - run-mypy:
          requires:
            - install
          filters:
            <<: *tagged-filter

      - check-dist:
          requires:
            - install
          filters:
            <<: *tagged-filter

      - upload-pypi:
          context: pypi-credentials
          requires:
            - run-flake8
            - run-black
            - run-pytest
            - run-mypy
            - install
          filters:
            <<: *tagged-filter
            branches:
              ignore: /.*/

      - build-docker-image:
          filters:
            <<: *tagged-filter

      - run-end2end-tests:
          filters:
            <<: *tagged-filter
          requires:
            - build-docker-image

      - deploy-docker-image:
          context: docker-credentials
          filters:
            <<: *tagged-filter
            branches:
              only: master
          requires:
            - run-flake8
            - run-black
            - run-pytest
            - run-mypy
            - install
            - build-docker-image
