#! /usr/bin/env bash

set -e

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

version=$(python -c 'import pkg_resources; print(pkg_resources.get_distribution("eth-index").version.replace("+", "_"))')

echo "Tagging with $version"
echo "=====> pushing to dockerhub"

set -x

docker tag ethindex trustlines/py-eth-index:$version
docker push trustlines/py-eth-index:$version

docker tag ethindex trustlines/py-eth-index:latest
docker push trustlines/py-eth-index:latest
